import Link from "next/link";
import { AppHeader } from "@/components/AppHeader";
import { Footer } from "@/components/Footer";

export default function PrivacyPage() {
  const updated = "March 24, 2026";

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <AppHeader />
      <main className="flex-1 pt-[120px] md:pt-[88px] pb-20 md:pb-0">
        <div className="container max-w-3xl py-10 md:py-14">
          <div className="mb-10">
            <h1 className="text-display font-bold mb-2">Privacy Policy</h1>
            <p className="text-small text-muted-foreground">Last updated: {updated}</p>
          </div>

          <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-body">

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">1. Who we are</h2>
              <p className="text-muted-foreground leading-relaxed">
                Polys is a prediction market intelligence platform that tracks real-time odds,
                arbitrage opportunities, and market sentiment across Polymarket, Kalshi, and
                other prediction markets. References to &ldquo;Polys,&rdquo; &ldquo;we,&rdquo;
                &ldquo;us,&rdquo; or &ldquo;our&rdquo; in this policy refer to the Polys service.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">2. Information we collect</h2>
              <p className="text-muted-foreground leading-relaxed">
                We collect information you provide directly when creating an account (name,
                email address, password) and information generated by your use of the service
                (pages viewed, features used, search queries). We do not collect payment card
                numbers directly — billing is handled by our payment processor.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">3. How we use your information</h2>
              <ul className="list-disc pl-5 space-y-1.5 text-muted-foreground">
                <li>To provide, operate, and maintain the Polys service</li>
                <li>To authenticate you and manage your account</li>
                <li>To send transactional emails (account confirmation, password resets)</li>
                <li>To send service notifications if you have opted in</li>
                <li>To improve and develop new features based on aggregate usage patterns</li>
                <li>To enforce our Terms of Service and comply with legal obligations</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">4. Cookies and local storage</h2>
              <p className="text-muted-foreground leading-relaxed">
                We use authentication cookies managed by Supabase to keep you signed in. We
                also store your display preferences (theme, density, font size) in your
                browser&rsquo;s local storage. We do not use advertising or cross-site
                tracking cookies.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">5. Data sharing</h2>
              <p className="text-muted-foreground leading-relaxed">
                We do not sell your personal information. We share data only with service
                providers necessary to operate Polys (authentication, hosting, email delivery,
                payment processing), and only to the extent required to provide those services.
                We may disclose information if required by law or to protect the rights and
                safety of our users.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">6. Data retention</h2>
              <p className="text-muted-foreground leading-relaxed">
                We retain your account information for as long as your account is active or as
                needed to provide the service. You may request deletion of your account and
                associated data at any time by contacting us.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">7. Your rights</h2>
              <p className="text-muted-foreground leading-relaxed">
                Depending on your location, you may have the right to access, correct, or
                delete the personal information we hold about you, and to object to or
                restrict certain processing. To exercise any of these rights, contact us at
                the address below.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">8. Security</h2>
              <p className="text-muted-foreground leading-relaxed">
                We use industry-standard security practices including encrypted connections
                (HTTPS), hashed passwords, and access controls. No method of transmission
                over the internet is 100% secure, and we cannot guarantee absolute security.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">9. Changes to this policy</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update this Privacy Policy from time to time. We will notify registered
                users of material changes via email or in-app notice. Continued use of Polys
                after changes take effect constitutes your acceptance of the updated policy.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-subtitle font-semibold">10. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                For questions or requests regarding this Privacy Policy, please contact us
                through our support channels. You can also review our{" "}
                <Link href="/terms" className="text-primary hover:underline">
                  Terms of Service
                </Link>
                .
              </p>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
